import { HTTP_METHODS, type OpenApiDocument, refName } from './schema.ts';

const bunPath = (template: string): string => template.replace(/\{(\w+)\}/g, ':$1');

const bodySchema = (op: { requestBody?: { content?: Record<string, { schema?: { $ref?: string } }> } }): string | undefined => {
  const ref = op.requestBody?.content?.['application/json']?.schema?.$ref;
  return ref === undefined ? undefined : refName(ref);
};

export function emitRoutes(doc: OpenApiDocument): string {
  const rows: string[] = [];

  for (const [template, item] of Object.entries(doc.paths)) {
    for (const method of HTTP_METHODS) {
      const op = item[method];
      if (op === undefined) continue;
      const operationId = op.operationId ?? `${method}${template}`;
      const security = (op.security ?? []).flatMap((s) => Object.keys(s));
      const params = (op.parameters ?? []).map(
        (p) => `{ name: ${JSON.stringify(p.name)}, in: ${JSON.stringify(p.in)}, required: ${p.required === true} }`,
      );
      const body = bodySchema(op);
      const statuses = Object.keys(op.responses ?? {}).sort();

      rows.push(
        [
          '  {',
          `    operationId: ${JSON.stringify(operationId)},`,
          `    method: ${JSON.stringify(method.toUpperCase())},`,
          `    path: ${JSON.stringify(template)},`,
          `    pattern: ${JSON.stringify(bunPath(template))},`,
          `    security: [${security.map((s) => JSON.stringify(s)).join(', ')}],`,
          `    params: [${params.join(', ')}],`,
          `    requestSchema: ${body === undefined ? 'undefined' : JSON.stringify(body)},`,
          `    statuses: [${statuses.map((s) => JSON.stringify(s)).join(', ')}],`,
          `    deprecated: ${op.deprecated === true},`,
          '  },',
        ].join('\n'),
      );
    }
  }

  return `// Generated by tools/spec-sync. Do not edit.

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export interface RouteParam {
  name: string;
  in: 'path' | 'query' | 'header';
  required: boolean;
}

export interface RouteSpec {
  operationId: string;
  method: HttpMethod;
  /** OpenAPI template, e.g. /v1/payments/{id} */
  path: string;
  /** Bun.serve pattern, e.g. /v1/payments/:id */
  pattern: string;
  security: string[];
  params: RouteParam[];
  requestSchema: string | undefined;
  statuses: string[];
  deprecated: boolean;
}

export const ROUTES: readonly RouteSpec[] = [
${rows.join('\n')}
];

export const ROUTES_BY_ID: ReadonlyMap<string, RouteSpec> = new Map(
  ROUTES.map((r) => [r.operationId, r]),
);
`;
}
