import { type JsonSchema, normalise, refName } from './schema.ts';

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const key = (name: string): string => (IDENT.test(name) ? name : JSON.stringify(name));
const lit = (v: string | number): string => (typeof v === 'number' ? String(v) : JSON.stringify(v));

export function typeExpr(schema: JsonSchema, indent: string): string {
  if (schema.$ref !== undefined) return refName(schema.$ref);

  const { types, nullable } = normalise(schema);
  const suffix = nullable ? ' | null' : '';

  if (schema.enum !== undefined && schema.enum.length > 0) {
    return schema.enum.map(lit).join(' | ') + suffix;
  }
  if (types.includes('array')) {
    const item = schema.items === undefined ? 'unknown' : typeExpr(schema.items, indent);
    return `${item.includes('|') || item.includes('{') ? `(${item})` : item}[]${suffix}`;
  }
  if (schema.properties !== undefined) return objectExpr(schema, indent) + suffix;
  if (types.includes('object')) return `Record<string, unknown>${suffix}`;
  if (types.includes('string')) return `string${suffix}`;
  if (types.includes('integer') || types.includes('number')) return `number${suffix}`;
  if (types.includes('boolean')) return `boolean${suffix}`;
  return 'unknown';
}

function objectExpr(schema: JsonSchema, indent: string): string {
  const inner = `${indent}  `;
  const required = new Set(schema.required ?? []);
  const lines = Object.entries(schema.properties ?? {}).map(([name, prop]) => {
    const optional = required.has(name) ? '' : '?';
    return `${inner}${key(name)}${optional}: ${typeExpr(prop, inner)};`;
  });
  return lines.length === 0 ? 'Record<string, unknown>' : `{\n${lines.join('\n')}\n${indent}}`;
}

export function emitTypes(schemas: Record<string, JsonSchema>): string {
  const out: string[] = ['// Generated by tools/spec-sync. Do not edit.', ''];
  for (const [name, schema] of Object.entries(schemas)) {
    if (schema.description !== undefined) out.push(`/** ${schema.description.replace(/\s+/g, ' ').trim()} */`);
    const body = typeExpr(schema, '');
    out.push(body.startsWith('{') ? `export interface ${name} ${body}` : `export type ${name} = ${body};`, '');
  }
  return out.join('\n');
}
