import { type JsonSchema, normalise, refName } from './schema.ts';

const PRELUDE = `// Generated by tools/spec-sync. Do not edit.
import { type Result, err, ok } from '@payground/core';
import type * as T from './types.ts';

export interface Issue {
  path: string;
  message: string;
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}
`;

class Emitter {
  private counter = 0;
  readonly lines: string[] = [];

  private next(): string {
    return `v${++this.counter}`;
  }

  private push(indent: string, line: string): void {
    this.lines.push(indent + line);
  }

  /** Emits checks for `expr`. Returns false when the schema constrains nothing. */
  check(schema: JsonSchema, expr: string, path: string, indent: string): boolean {
    if (schema.$ref !== undefined) {
      this.push(indent, `check${refName(schema.$ref)}(${expr}, ${path}, out);`);
      return true;
    }

    const { types, nullable } = normalise(schema);
    const body: string[] = [];
    const inner = nullable ? `${indent}  ` : indent;
    const mark = this.lines.length;

    if (nullable) this.push(indent, `if (${expr} !== null) {`);

    let emitted = true;
    if (schema.enum !== undefined && schema.enum.length > 0) {
      const test = schema.enum.map((v) => `${expr} !== ${JSON.stringify(v)}`).join(' && ');
      this.push(inner, `if (${test}) out.push({ path: ${path}, message: 'not one of the allowed values' });`);
    } else if (types.includes('array')) {
      this.push(inner, `if (!Array.isArray(${expr})) {`);
      this.push(inner, `  out.push({ path: ${path}, message: 'expected array' });`);
      if (schema.items === undefined) {
        this.push(inner, `}`);
      } else {
        this.push(inner, `} else {`);
        const i = this.next();
        const e = this.next();
        this.push(inner, `  for (let ${i} = 0; ${i} < ${expr}.length; ${i}++) {`);
        this.push(inner, `    const ${e}: unknown = ${expr}[${i}];`);
        const wrote = this.check(schema.items, e, `${path} + '[' + ${i} + ']'`, `${inner}    `);
        if (!wrote) this.push(inner, `    void ${e};`);
        this.push(inner, `  }`);
        this.push(inner, `}`);
      }
    } else if (schema.properties !== undefined) {
      this.object(schema, expr, path, inner);
    } else if (types.includes('object')) {
      this.push(inner, `if (!isObject(${expr})) out.push({ path: ${path}, message: 'expected object' });`);
    } else if (types.includes('string')) {
      this.push(inner, `if (typeof ${expr} !== 'string') out.push({ path: ${path}, message: 'expected string' });`);
    } else if (types.includes('integer')) {
      this.push(inner, `if (typeof ${expr} !== 'number' || !Number.isInteger(${expr})) out.push({ path: ${path}, message: 'expected integer' });`);
    } else if (types.includes('number')) {
      this.push(inner, `if (typeof ${expr} !== 'number' || !Number.isFinite(${expr})) out.push({ path: ${path}, message: 'expected number' });`);
    } else if (types.includes('boolean')) {
      this.push(inner, `if (typeof ${expr} !== 'boolean') out.push({ path: ${path}, message: 'expected boolean' });`);
    } else {
      emitted = false;
    }

    if (schema.minimum !== undefined && (types.includes('number') || types.includes('integer'))) {
      this.push(inner, `if (typeof ${expr} === 'number' && ${expr} < ${schema.minimum}) out.push({ path: ${path}, message: 'below minimum ${schema.minimum}' });`);
      emitted = true;
    }

    if (nullable) {
      if (!emitted) {
        this.lines.length = mark;
        return false;
      }
      this.push(indent, `}`);
    }
    void body;
    return emitted;
  }

  object(schema: JsonSchema, expr: string, path: string, indent: string): void {
    this.push(indent, `if (!isObject(${expr})) {`);
    this.push(indent, `  out.push({ path: ${path}, message: 'expected object' });`);
    this.push(indent, `} else {`);
    const required = new Set(schema.required ?? []);
    for (const [name, prop] of Object.entries(schema.properties ?? {})) {
      const local = this.next();
      const propPath = `${path} + ${JSON.stringify(`.${name}`)}`;
      const mark = this.lines.length;
      this.push(indent, `  const ${local}: unknown = ${expr}[${JSON.stringify(name)}];`);
      if (required.has(name)) {
        this.push(indent, `  if (${local} === undefined) {`);
        this.push(indent, `    out.push({ path: ${propPath}, message: 'required' });`);
        this.push(indent, `  } else {`);
        const wrote = this.check(prop, local, propPath, `${indent}    `);
        if (!wrote) this.push(indent, `    void ${local};`);
        this.push(indent, `  }`);
      } else {
        this.push(indent, `  if (${local} !== undefined) {`);
        const wrote = this.check(prop, local, propPath, `${indent}    `);
        if (!wrote) {
          this.lines.length = mark;
          continue;
        }
        this.push(indent, `  }`);
      }
    }
    this.push(indent, `}`);
  }
}

export function emitValidators(schemas: Record<string, JsonSchema>): string {
  const out: string[] = [PRELUDE];

  for (const [name, schema] of Object.entries(schemas)) {
    const emitter = new Emitter();
    const wrote = emitter.check(schema, 'value', 'path', '  ');
    out.push(`export function check${name}(value: unknown, path: string, out: Issue[]): void {`);
    if (wrote) out.push(emitter.lines.join('\n'));
    else out.push('  void value;\n  void path;\n  void out;');
    out.push('}', '');
    out.push(
      `export function validate${name}(value: unknown): Result<T.${name}, Issue[]> {`,
      '  const issues: Issue[] = [];',
      `  check${name}(value, '', issues);`,
      '  return issues.length === 0 ? ok(value as T.' + name + ') : err(issues);',
      '}',
      '',
    );
  }

  return out.join('\n');
}
