import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { DIVERGENCES, OVERLAY } from '../../../spec/overlay.ts';
import { emitRoutes } from './emit-routes.ts';
import { emitTypes } from './emit-types.ts';
import { emitValidators } from './emit-validate.ts';
import type { JsonSchema, OpenApiDocument } from './schema.ts';

const ROOT = join(import.meta.dir, '../../..');
const OUT = join(ROOT, 'packages/mercadopago/src/generated');

export function applyOverlay(doc: OpenApiDocument): Record<string, JsonSchema> {
  const schemas: Record<string, JsonSchema> = structuredClone(doc.components.schemas);
  for (const entry of OVERLAY) {
    const target = schemas[entry.schema];
    if (target === undefined) throw new Error(`overlay targets unknown schema: ${entry.schema}`);
    for (const [name, prop] of Object.entries(entry.properties ?? {})) {
      target.properties = { ...target.properties, [name]: prop };
    }
    if (entry.required !== undefined) {
      target.required = [...new Set([...(target.required ?? []), ...entry.required])];
    }
  }
  return schemas;
}

export function emitFidelity(): string {
  const lines = [
    '# Fidelity',
    '',
    'Generated by `bun run spec:gen`. Do not edit by hand.',
    '',
    'Every known divergence between payground and the real Mercado Pago API is recorded',
    'here, because it is impossible to add one without writing its entry.',
    '',
    '## Schema gaps filled by the overlay',
    '',
    'The vendored OpenAPI specification omits fields the API returns. These are added back,',
    'with the source the shape came from.',
    '',
  ];
  for (const entry of OVERLAY) {
    const props = Object.keys(entry.properties ?? {});
    lines.push(
      `### \`${entry.schema}\``,
      '',
      entry.note,
      '',
      props.length > 0 ? `Added: ${props.map((p) => `\`${p}\``).join(', ')}` : '',
      '',
      `Source: ${entry.source}`,
      '',
    );
  }
  lines.push('## Behavioural divergences', '');
  for (const d of DIVERGENCES) {
    lines.push(`### ${d.area} — ${d.summary}`, '', d.detail, '', `Source: ${d.source}`, '');
  }
  return lines.filter((l, i, a) => !(l === '' && a[i - 1] === '')).join('\n');
}

async function main(): Promise<void> {
  const doc = (await Bun.file(join(ROOT, 'spec/spec3.json')).json()) as OpenApiDocument;
  const schemas = applyOverlay(doc);

  await mkdir(OUT, { recursive: true });
  await writeFile(join(OUT, 'types.ts'), emitTypes(schemas));
  await writeFile(join(OUT, 'validate.ts'), emitValidators(schemas));
  await writeFile(join(OUT, 'routes.ts'), emitRoutes(doc));
  await writeFile(join(ROOT, 'FIDELITY.md'), `${emitFidelity()}\n`);

  console.log(`${Object.keys(schemas).length} schemas, ${Object.keys(doc.paths).length} paths`);
}

if (import.meta.main) await main();
