import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { DIVERGENCES, OVERLAY } from '../../../spec/overlay.ts';
import { emitRoutes } from './emit-routes.ts';
import { emitTypes } from './emit-types.ts';
import { emitValidators } from './emit-validate.ts';
import type { JsonSchema, OpenApiDocument } from './schema.ts';

const ROOT = join(import.meta.dir, '../../..');
const OUT = join(ROOT, 'packages/mercadopago/src/generated');

export function applyOverlay(doc: OpenApiDocument): Record<string, JsonSchema> {
  const schemas: Record<string, JsonSchema> = structuredClone(doc.components.schemas);
  for (const entry of OVERLAY) {
    const target = schemas[entry.schema];
    if (target === undefined) throw new Error(`overlay targets unknown schema: ${entry.schema}`);
    for (const [name, prop] of Object.entries(entry.properties ?? {})) {
      target.properties = { ...target.properties, [name]: prop };
    }
    if (entry.required !== undefined) {
      target.required = [...new Set([...(target.required ?? []), ...entry.required])];
    }
  }
  return schemas;
}

export function emitFidelity(): string {
  const areas = [...new Set(DIVERGENCES.map((d) => d.area))].sort();
  const lines = [
    '# Fidelity',
    '',
    'Every known difference between payground and the real Mercado Pago API, so you can tell',
    'what will change the day you point the same code at `api.mercadopago.com`.',
    '',
    'It is generated by `bun run spec:gen` from `spec/overlay.ts`, so do not edit it by hand.',
    'A schema gap cannot go undocumented: the overlay is the only way to widen a generated type,',
    'and an entry does not compile without its prose and the source the shape came from. The',
    'behavioural entries are written by hand, one per decision payground had to make.',
    '',
    `${OVERLAY.length} schema gaps, ${DIVERGENCES.length} behavioural divergences across ${areas.length} areas.`,
    '',
    '## Schema gaps filled by the overlay',
    '',
    'The vendored OpenAPI specification omits fields the API returns. These are added back,',
    'with the source the shape came from.',
    '',
  ];
  for (const entry of OVERLAY) {
    const props = Object.keys(entry.properties ?? {});
    lines.push(
      `### \`${entry.schema}\``,
      '',
      entry.note,
      '',
      props.length > 0 ? `Added: ${props.map((p) => `\`${p}\``).join(', ')}` : '',
      '',
      `Source: ${entry.source}`,
      '',
    );
  }
  lines.push(
    '## Behavioural divergences',
    '',
    'Differences that are not schema-shaped: status vocabularies, endpoints the specification',
    'never documented, and outcomes payground had to choose. Grouped by area.',
    '',
  );
  for (const area of areas) {
    lines.push(`### ${area}`, '');
    for (const d of DIVERGENCES.filter((entry) => entry.area === area)) {
      lines.push(`#### ${d.summary}`, '', d.detail, '', `Source: ${d.source}`, '');
    }
  }
  return lines.filter((l, i, a) => !(l === '' && a[i - 1] === '')).join('\n');
}

async function main(): Promise<void> {
  const doc = (await Bun.file(join(ROOT, 'spec/spec3.json')).json()) as OpenApiDocument;
  const schemas = applyOverlay(doc);

  await mkdir(OUT, { recursive: true });
  await writeFile(join(OUT, 'types.ts'), emitTypes(schemas));
  await writeFile(join(OUT, 'validate.ts'), emitValidators(schemas));
  await writeFile(join(OUT, 'routes.ts'), emitRoutes(doc));
  await writeFile(join(ROOT, 'FIDELITY.md'), `${emitFidelity()}\n`);

  console.log(`${Object.keys(schemas).length} schemas, ${Object.keys(doc.paths).length} paths`);
}

if (import.meta.main) await main();
